### ISSUE TITLE
Can't import when using Gradle

### ISSUE THREAD

**Issue by CrystalENVT** [BazzaDEV/SimpleMenus#1]
The project seems great, but I can't import SimpleMenus into my project in IntelliJ when I download the project with Gradle.

Gradle:
```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

apply plugin: 'application'
mainClassName = 'com.snreloaded.TestApp'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    // BazzaDEV => SimpleMenus
    implementation 'com.github.BazzaDEV:SimpleMenus:1.2.1'
}

test {
    useJUnitPlatform()
}
```

The example app from the ReadMe then has errors for every `options` component at the top. Here is the format of the downloaded Jar (in hopes it will assist in debugging) 
![image](https://user-images.githubusercontent.com/6373584/131263482-bfcb0432-1e36-4df1-af31-c8931dcca7f1.png)

**Comment by kianbazza** [comment]
I updated the [example class](https://gist.github.com/BazzaDEV/5293820b8b183040f0b749f67ef6c2cf) that was provided in the README and it is working for me now on a fresh project. Let me know if it works now!

**Comment by CrystalENVT** [comment]
Unfortunately, no this still doesn't work. 
![image](https://user-images.githubusercontent.com/6373584/131429886-8be58ccd-cd4e-4776-babd-7b5282bfeb92.png)
As you can see in the above screenshot, any reference to Menu is still broken. When I press Alt+Enter to try & import `Menu`, it just imports `java.awt.*`

**Comment by kianbazza** [comment]
I'm honestly not sure what the issue is. I use Maven (so I'm pretty green when it comes to Gradle), but managed to get everything working fairly smoothly by doing the following:
- Make new IntelliJ Gradle Java project
- Use the instructions in the README to add SimpleMenus dependency
- Add the example class to my src/main/java directory
- All classes are imported correctly

Could you provide your build.gradle (or even better, the whole project) to help with debugging?

**Comment by CrystalENVT** [comment]
Interesting, I'll try that out this evening. If you look int he above picture, you can see I have my class in src/main/java/com/snreloaded

I provided the entirety of my build.gradle in my first post in this thread, but I can zip up my project to send it along for testing

**Comment by kianbazza** [comment]
I started running into the same issues as you once I put the example class within a package. I have got it working on my side now, try again using `implementation 'com.github.BazzaDEV:SimpleMenus:1.2.2-BETA-SNAPSHOT'` in dependencies & let me know how it goes.

**Comment by CrystalENVT** [comment]
This Beta **mostly** works. I can't alt+enter to auto import (still defaults to java.awt.*), but if I manually type in `import objects.Menu;` the import works. Perhaps this is an issue with Jitpack or the configuration?

However, this IS at a point that I can start working with the framework. I am happy to continue helping with troubleshooting this if you want to continue work on this.

**Comment by CrystalENVT** [comment]
I have also noticed that you have your code just in the root of the src/main/java directory. While this is fine for personal projects, I think the industry standard is to have a `src/main/java/com/<developer_name OR organization_name>`, which might be why the gradle packaging is having issues?

**Comment by kianbazza** [comment]
> This Beta **mostly** works. I can't alt+enter to auto import (still defaults to java.awt.*), but if I manually type in `import objects.Menu;` the import works. Perhaps this is an issue with Jitpack or the configuration?

1.2.3-BETA should account for this, if the previous one didn't. You can import it using: 
`implementation 'com.github.BazzaDEV:SimpleMenus:1.2.3-BETA'`

Let me know if the auto-import works for you now.

> I have also noticed that you have your code just in the root of the src/main/java directory. While this is fine for personal projects, I think the industry standard is to have a `src/main/java/com/<developer_name OR organization_name>`, which might be why the gradle packaging is having issues?

Good catch, I have fixed this in the new beta as well.

Thank you for the help, I haven't had much time to give this project any attention (wrote this up overnight to assist with a school project, and haven't touched it since). Will be cleaning up the code & adding some new features, let me know if you have any suggestions 😄

**Comment by CrystalENVT** [comment]
Can confirm that `1.2.3-BETA` works for this. In regards to the purpose of this issue, it can probably be closed.

As far as other ideas, the current menu system seems decent for the most simple menu setup. I don't really know what else you could add without having a `curses`/`ncurses` type setup (something like [this video at the 8:15](https://youtu.be/3YiPdibiQHA?t=495) mark).

There is the project [Lanterna](https://github.com/mabe02/lanterna) that provides this, but it is complex to set up for a simple selection menu.

This might be scope creep, but my dream for a simple curses-like menu would be to pass in an (array)list of strings, & get the index of the list back that was selected.

**Comment by kianbazza** [comment]
That looks super clean, I'll look into adding it if it's possible. Above all, my priority is simplicity and ease-of-use - but if I can implement that while meeting those two goals then I'll get it done!
